import { DateTime } from 'luxon';

const countryTimezones: { [key: string]: string } = {
  // Europe
  'United Kingdom': 'Europe/London',
  'Italy': 'Europe/Rome',
  'Germany': 'Europe/Berlin',
  'France': 'Europe/Paris',
  'Spain': 'Europe/Madrid',
  'Netherlands': 'Europe/Amsterdam',
  'Belgium': 'Europe/Brussels',
  'Switzerland': 'Europe/Zurich',
  'Austria': 'Europe/Vienna',
  'Portugal': 'Europe/Lisbon',
  'Greece': 'Europe/Athens',
  'Poland': 'Europe/Warsaw',
  'Czech Republic': 'Europe/Prague',
  'Hungary': 'Europe/Budapest',
  'Romania': 'Europe/Bucharest',
  'Bulgaria': 'Europe/Sofia',
  'Croatia': 'Europe/Zagreb',
  'Slovenia': 'Europe/Ljubljana',
  'Slovakia': 'Europe/Bratislava',
  'Lithuania': 'Europe/Vilnius',
  'Latvia': 'Europe/Riga',
  'Estonia': 'Europe/Tallinn',
  'Finland': 'Europe/Helsinki',
  'Sweden': 'Europe/Stockholm',
  'Norway': 'Europe/Oslo',
  'Denmark': 'Europe/Copenhagen',
  'Iceland': 'Atlantic/Reykjavik',
  'Ireland': 'Europe/Dublin',
  'Malta': 'Europe/Malta',
  'Cyprus': 'Asia/Nicosia',
  'Luxembourg': 'Europe/Luxembourg',
  'Monaco': 'Europe/Monaco',
  'San Marino': 'Europe/San_Marino',
  'Vatican City': 'Europe/Vatican',
  'Andorra': 'Europe/Andorra',
  'Liechtenstein': 'Europe/Vaduz',
  'Serbia': 'Europe/Belgrade',
  'Montenegro': 'Europe/Podgorica',
  'Bosnia and Herzegovina': 'Europe/Sarajevo',
  'North Macedonia': 'Europe/Skopje',
  'Albania': 'Europe/Tirane',
  'Kosovo': 'Europe/Belgrade',
  'Moldova': 'Europe/Chisinau',
  'Ukraine': 'Europe/Kiev',
  'Belarus': 'Europe/Minsk',
  'Russia': 'Europe/Moscow',
  'Turkey': 'Europe/Istanbul',

  // North America
  'United States': 'America/New_York',
  'USA': 'America/New_York',
  'Canada': 'America/Toronto',
  'Mexico': 'America/Mexico_City',
  'Guatemala': 'America/Guatemala',
  'Belize': 'America/Belize',
  'El Salvador': 'America/El_Salvador',
  'Honduras': 'America/Tegucigalpa',
  'Nicaragua': 'America/Managua',
  'Costa Rica': 'America/Costa_Rica',
  'Panama': 'America/Panama',

  // South America
  'Brazil': 'America/Sao_Paulo',
  'Argentina': 'America/Argentina/Buenos_Aires',
  'Chile': 'America/Santiago',
  'Colombia': 'America/Bogota',
  'Peru': 'America/Lima',
  'Venezuela': 'America/Caracas',
  'Ecuador': 'America/Guayaquil',
  'Bolivia': 'America/La_Paz',
  'Paraguay': 'America/Asuncion',
  'Uruguay': 'America/Montevideo',
  'Guyana': 'America/Guyana',
  'Suriname': 'America/Paramaribo',
  'French Guiana': 'America/Cayenne',

  // Asia
  'China': 'Asia/Shanghai',
  'Japan': 'Asia/Tokyo',
  'South Korea': 'Asia/Seoul',
  'India': 'Asia/Kolkata',
  'Thailand': 'Asia/Bangkok',
  'Vietnam': 'Asia/Ho_Chi_Minh',
  'Singapore': 'Asia/Singapore',
  'Malaysia': 'Asia/Kuala_Lumpur',
  'Indonesia': 'Asia/Jakarta',
  'Philippines': 'Asia/Manila',
  'Taiwan': 'Asia/Taipei',
  'Hong Kong': 'Asia/Hong_Kong',
  'Macau': 'Asia/Macau',
  'Mongolia': 'Asia/Ulaanbaatar',
  'Kazakhstan': 'Asia/Almaty',
  'Uzbekistan': 'Asia/Tashkent',
  'Kyrgyzstan': 'Asia/Bishkek',
  'Tajikistan': 'Asia/Dushanbe',
  'Turkmenistan': 'Asia/Ashgabat',
  'Afghanistan': 'Asia/Kabul',
  'Pakistan': 'Asia/Karachi',
  'Bangladesh': 'Asia/Dhaka',
  'Sri Lanka': 'Asia/Colombo',
  'Nepal': 'Asia/Kathmandu',
  'Bhutan': 'Asia/Thimphu',
  'Myanmar': 'Asia/Yangon',
  'Laos': 'Asia/Vientiane',
  'Cambodia': 'Asia/Phnom_Penh',
  'Brunei': 'Asia/Brunei',
  'East Timor': 'Asia/Dili',
  'North Korea': 'Asia/Pyongyang',
  'Iran': 'Asia/Tehran',
  'Iraq': 'Asia/Baghdad',
  'Syria': 'Asia/Damascus',
  'Lebanon': 'Asia/Beirut',
  'Jordan': 'Asia/Amman',
  'Israel': 'Asia/Jerusalem',
  'Palestine': 'Asia/Gaza',
  'Saudi Arabia': 'Asia/Riyadh',
  'Kuwait': 'Asia/Kuwait',
  'Bahrain': 'Asia/Bahrain',
  'Qatar': 'Asia/Qatar',
  'United Arab Emirates': 'Asia/Dubai',
  'UAE': 'Asia/Dubai',
  'Oman': 'Asia/Muscat',
  'Yemen': 'Asia/Aden',
  'Georgia': 'Asia/Tbilisi',
  'Armenia': 'Asia/Yerevan',
  'Azerbaijan': 'Asia/Baku',

  // Africa
  'South Africa': 'Africa/Johannesburg',
  'Egypt': 'Africa/Cairo',
  'Nigeria': 'Africa/Lagos',
  'Kenya': 'Africa/Nairobi',
  'Morocco': 'Africa/Casablanca',
  'Algeria': 'Africa/Algiers',
  'Tunisia': 'Africa/Tunis',
  'Libya': 'Africa/Tripoli',
  'Sudan': 'Africa/Khartoum',
  'Ethiopia': 'Africa/Addis_Ababa',
  'Ghana': 'Africa/Accra',
  'Ivory Coast': 'Africa/Abidjan',
  'Senegal': 'Africa/Dakar',
  'Mali': 'Africa/Bamako',
  'Burkina Faso': 'Africa/Ouagadougou',
  'Niger': 'Africa/Niamey',
  'Chad': 'Africa/Ndjamena',
  'Cameroon': 'Africa/Douala',
  'Central African Republic': 'Africa/Bangui',
  'Democratic Republic of the Congo': 'Africa/Kinshasa',
  'Republic of the Congo': 'Africa/Brazzaville',
  'Gabon': 'Africa/Libreville',
  'Equatorial Guinea': 'Africa/Malabo',
  'Sao Tome and Principe': 'Africa/Sao_Tome',
  'Angola': 'Africa/Luanda',
  'Zambia': 'Africa/Lusaka',
  'Zimbabwe': 'Africa/Harare',
  'Botswana': 'Africa/Gaborone',
  'Namibia': 'Africa/Windhoek',
  'Lesotho': 'Africa/Maseru',
  'Swaziland': 'Africa/Mbabane',
  'Mozambique': 'Africa/Maputo',
  'Madagascar': 'Africa/Antananarivo',
  'Mauritius': 'Indian/Mauritius',
  'Seychelles': 'Indian/Mahe',
  'Comoros': 'Indian/Comoro',
  'Mayotte': 'Indian/Mayotte',
  'Reunion': 'Indian/Reunion',
  'Tanzania': 'Africa/Dar_es_Salaam',
  'Uganda': 'Africa/Kampala',
  'Rwanda': 'Africa/Kigali',
  'Burundi': 'Africa/Bujumbura',
  'Djibouti': 'Africa/Djibouti',
  'Somalia': 'Africa/Mogadishu',
  'Eritrea': 'Africa/Asmara',
  'Malawi': 'Africa/Blantyre',
  'Guinea': 'Africa/Conakry',
  'Guinea-Bissau': 'Africa/Bissau',
  'Sierra Leone': 'Africa/Freetown',
  'Liberia': 'Africa/Monrovia',
  'Togo': 'Africa/Lome',
  'Benin': 'Africa/Porto-Novo',
  'Cape Verde': 'Atlantic/Cape_Verde',
  'Gambia': 'Africa/Banjul',

  // Oceania
  'Australia': 'Australia/Sydney',
  'New Zealand': 'Pacific/Auckland',
  'Fiji': 'Pacific/Fiji',
  'Papua New Guinea': 'Pacific/Port_Moresby',
  'Solomon Islands': 'Pacific/Guadalcanal',
  'Vanuatu': 'Pacific/Efate',
  'New Caledonia': 'Pacific/Noumea',
  'French Polynesia': 'Pacific/Tahiti',
  'Samoa': 'Pacific/Apia',
  'Tonga': 'Pacific/Tongatapu',
  'Cook Islands': 'Pacific/Rarotonga',
  'Kiribati': 'Pacific/Tarawa',
  'Tuvalu': 'Pacific/Funafuti',
  'Nauru': 'Pacific/Nauru',
  'Marshall Islands': 'Pacific/Majuro',
  'Micronesia': 'Pacific/Chuuk',
  'Palau': 'Pacific/Palau',
  'Guam': 'Pacific/Guam',
  'Northern Mariana Islands': 'Pacific/Saipan',
  'American Samoa': 'Pacific/Pago_Pago',

  // Common alternative names
  'UK': 'Europe/London',
  'GB': 'Europe/London',
  'US': 'America/New_York',
  'IT': 'Europe/Rome',
  'DE': 'Europe/Berlin',
  'FR': 'Europe/Paris',
  'ES': 'Europe/Madrid',
  'NL': 'Europe/Amsterdam',
  'BE': 'Europe/Brussels',
  'CH': 'Europe/Zurich',
  'AT': 'Europe/Vienna',
  'PT': 'Europe/Lisbon',
  'GR': 'Europe/Athens',
  'PL': 'Europe/Warsaw',
  'CZ': 'Europe/Prague',
  'HU': 'Europe/Budapest',
  'RO': 'Europe/Bucharest',
  'BG': 'Europe/Sofia',
  'HR': 'Europe/Zagreb',
  'SI': 'Europe/Ljubljana',
  'SK': 'Europe/Bratislava',
  'LT': 'Europe/Vilnius',
  'LV': 'Europe/Riga',
  'EE': 'Europe/Tallinn',
  'FI': 'Europe/Helsinki',
  'SE': 'Europe/Stockholm',
  'NO': 'Europe/Oslo',
  'DK': 'Europe/Copenhagen',
  'IS': 'Atlantic/Reykjavik',
  'IE': 'Europe/Dublin',
  'MT': 'Europe/Malta',
  'CY': 'Asia/Nicosia',
  'LU': 'Europe/Luxembourg',
  'MC': 'Europe/Monaco',
  'SM': 'Europe/San_Marino',
  'VA': 'Europe/Vatican',
  'AD': 'Europe/Andorra',
  'LI': 'Europe/Vaduz',
  'RS': 'Europe/Belgrade',
  'ME': 'Europe/Podgorica',
  'BA': 'Europe/Sarajevo',
  'MK': 'Europe/Skopje',
  'AL': 'Europe/Tirane',
  'XK': 'Europe/Belgrade',
  'MD': 'Europe/Chisinau',
  'UA': 'Europe/Kiev',
  'BY': 'Europe/Minsk',
  'RU': 'Europe/Moscow',
  'TR': 'Europe/Istanbul',
  'CA': 'America/Toronto',
  'MX': 'America/Mexico_City',
  'GT': 'America/Guatemala',
  'BZ': 'America/Belize',
  'SV': 'America/El_Salvador',
  'HN': 'America/Tegucigalpa',
  'NI': 'America/Managua',
  'CR': 'America/Costa_Rica',
  'PA': 'America/Panama',
  'BR': 'America/Sao_Paulo',
  'AR': 'America/Argentina/Buenos_Aires',
  'CL': 'America/Santiago',
  'CO': 'America/Bogota',
  'PE': 'America/Lima',
  'VE': 'America/Caracas',
  'EC': 'America/Guayaquil',
  'BO': 'America/La_Paz',
  'PY': 'America/Asuncion',
  'UY': 'America/Montevideo',
  'GY': 'America/Guyana',
  'SR': 'America/Paramaribo',
  'GF': 'America/Cayenne',
  'CN': 'Asia/Shanghai',
  'JP': 'Asia/Tokyo',
  'KR': 'Asia/Seoul',
  'IN': 'Asia/Kolkata',
  'TH': 'Asia/Bangkok',
  'VN': 'Asia/Ho_Chi_Minh',
  'SG': 'Asia/Singapore',
  'MY': 'Asia/Kuala_Lumpur',
  'ID': 'Asia/Jakarta',
  'PH': 'Asia/Manila',
  'TW': 'Asia/Taipei',
  'HK': 'Asia/Hong_Kong',
  'MO': 'Asia/Macau',
  'MN': 'Asia/Ulaanbaatar',
  'KZ': 'Asia/Almaty',
  'UZ': 'Asia/Tashkent',
  'KG': 'Asia/Bishkek',
  'TJ': 'Asia/Dushanbe',
  'TM': 'Asia/Ashgabat',
  'AF': 'Asia/Kabul',
  'PK': 'Asia/Karachi',
  'BD': 'Asia/Dhaka',
  'LK': 'Asia/Colombo',
  'NP': 'Asia/Kathmandu',
  'BT': 'Asia/Thimphu',
  'MM': 'Asia/Yangon',
  'LA': 'Asia/Vientiane',
  'KH': 'Asia/Phnom_Penh',
  'BN': 'Asia/Brunei',
  'TL': 'Asia/Dili',
  'KP': 'Asia/Pyongyang',
  'IR': 'Asia/Tehran',
  'IQ': 'Asia/Baghdad',
  'SY': 'Asia/Damascus',
  'LB': 'Asia/Beirut',
  'JO': 'Asia/Amman',
  'IL': 'Asia/Jerusalem',
  'PS': 'Asia/Gaza',
  'SA': 'Asia/Riyadh',
  'KW': 'Asia/Kuwait',
  'BH': 'Asia/Bahrain',
  'QA': 'Asia/Qatar',
  'AE': 'Asia/Dubai',
  'OM': 'Asia/Muscat',
  'YE': 'Asia/Aden',
  'GE': 'Asia/Tbilisi',
  'AM': 'Asia/Yerevan',
  'AZ': 'Asia/Baku',
  'ZA': 'Africa/Johannesburg',
  'EG': 'Africa/Cairo',
  'NG': 'Africa/Lagos',
  'KE': 'Africa/Nairobi',
  'MA': 'Africa/Casablanca',
  'DZ': 'Africa/Algiers',
  'TN': 'Africa/Tunis',
  'LY': 'Africa/Tripoli',
  'SD': 'Africa/Khartoum',
  'ET': 'Africa/Addis_Ababa',
  'GH': 'Africa/Accra',
  'CI': 'Africa/Abidjan',
  'SN': 'Africa/Dakar',
  'ML': 'Africa/Bamako',
  'BF': 'Africa/Ouagadougou',
  'NE': 'Africa/Niamey',
  'TD': 'Africa/Ndjamena',
  'CM': 'Africa/Douala',
  'CF': 'Africa/Bangui',
  'CD': 'Africa/Kinshasa',
  'CG': 'Africa/Brazzaville',
  'GA': 'Africa/Libreville',
  'GQ': 'Africa/Malabo',
  'ST': 'Africa/Sao_Tome',
  'AO': 'Africa/Luanda',
  'ZM': 'Africa/Lusaka',
  'ZW': 'Africa/Harare',
  'BW': 'Africa/Gaborone',
  'NA': 'Africa/Windhoek',
  'LS': 'Africa/Maseru',
  'SZ': 'Africa/Mbabane',
  'MZ': 'Africa/Maputo',
  'MG': 'Africa/Antananarivo',
  'MU': 'Indian/Mauritius',
  'SC': 'Indian/Mahe',
  'KM': 'Indian/Comoro',
  'YT': 'Indian/Mayotte',
  'RE': 'Indian/Reunion',
  'TZ': 'Africa/Dar_es_Salaam',
  'UG': 'Africa/Kampala',
  'RW': 'Africa/Kigali',
  'BI': 'Africa/Bujumbura',
  'DJ': 'Africa/Djibouti',
  'SO': 'Africa/Mogadishu',
  'ER': 'Africa/Asmara',
  'MW': 'Africa/Blantyre',
  'GN': 'Africa/Conakry',
  'GW': 'Africa/Bissau',
  'SL': 'Africa/Freetown',
  'LR': 'Africa/Monrovia',
  'TG': 'Africa/Lome',
  'BJ': 'Africa/Porto-Novo',
  'CV': 'Atlantic/Cape_Verde',
  'GM': 'Africa/Banjul',
  'AU': 'Australia/Sydney',
  'NZ': 'Pacific/Auckland',
  'FJ': 'Pacific/Fiji',
  'PG': 'Pacific/Port_Moresby',
  'SB': 'Pacific/Guadalcanal',
  'VU': 'Pacific/Efate',
  'NC': 'Pacific/Noumea',
  'PF': 'Pacific/Tahiti',
  'WS': 'Pacific/Apia',
  'TO': 'Pacific/Tongatapu',
  'CK': 'Pacific/Rarotonga',
  'KI': 'Pacific/Tarawa',
  'TV': 'Pacific/Funafuti',
  'NR': 'Pacific/Nauru',
  'MH': 'Pacific/Majuro',
  'FM': 'Pacific/Chuuk',
  'PW': 'Pacific/Palau',
  'GU': 'Pacific/Guam',
  'MP': 'Pacific/Saipan',
  'AS': 'Pacific/Pago_Pago'
};

export function getLocalTime(country: string | null): string {
  if (!country) return 'Unknown';
  
  const timezone = countryTimezones[country];
  if (!timezone) return 'Unknown';

  return DateTime.now().setZone(timezone).toFormat('HH:mm');
}